# Generated by Django 3.2.8 on 2021-10-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiGiang',
            fields=[
                ('MaBaiGiang', models.AutoField(primary_key=True, serialize=False)),
                ('MaKhoaHoc', models.CharField(max_length=100)),
                ('LinkBaiGiang', models.CharField(max_length=100)),
                ('LinkPoster', models.CharField(max_length=100)),
                ('SoThuTu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BinhLuan',
            fields=[
                ('MaBinhLuan', models.AutoField(primary_key=True, serialize=False)),
                ('MaKhoaHoc', models.CharField(max_length=100)),
                ('MaHocVien', models.CharField(max_length=100)),
                ('NoiDung', models.CharField(max_length=500)),
                ('ThoiGianBinhLuan', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('MaDanhGia', models.AutoField(primary_key=True, serialize=False)),
                ('MaKhoaHoc', models.CharField(max_length=100)),
                ('MaHocVien', models.CharField(max_length=100)),
                ('DiemDanhGia', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GiaoVien',
            fields=[
                ('MaGiaoVien', models.AutoField(primary_key=True, serialize=False)),
                ('TenGiaoVien', models.CharField(max_length=100)),
                ('AnhGiaoVien', models.CharField(max_length=100)),
                ('ThongTinGiaoVien', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='HocVien',
            fields=[
                ('MaHocVien', models.AutoField(primary_key=True, serialize=False)),
                ('TenHocVien', models.CharField(max_length=100)),
                ('EmailHocVien', models.CharField(max_length=100)),
                ('MatKhau', models.CharField(max_length=100)),
                ('NgaySinh', models.DateField()),
                ('AnhHocVien', models.CharField(max_length=100)),
                ('GioiTinh', models.CharField(max_length=100)),
                ('SoDuTaiKhoan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KhoaHoc',
            fields=[
                ('MaKhoaHoc', models.AutoField(primary_key=True, serialize=False)),
                ('TenKhoaHoc', models.CharField(max_length=100)),
                ('MaGiaoVien', models.CharField(max_length=100)),
                ('LinkAnhKhoaHoc', models.CharField(max_length=100)),
                ('LinkVideoBaiGiang', models.CharField(max_length=100)),
                ('GiaKhoaHoc', models.IntegerField()),
                ('KhuyenMai', models.IntegerField()),
                ('LoaiKhoaHoc', models.CharField(max_length=100)),
                ('ThongTinKhoaHoc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='KhoaHocHocVien',
            fields=[
                ('MaKetHop', models.AutoField(primary_key=True, serialize=False)),
                ('MaKhoaHoc', models.CharField(max_length=100)),
                ('MaHocVien', models.CharField(max_length=100)),
            ],
        ),
    ]
