# Generated by Django 3.2.8 on 2021-11-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('MaGioHang', models.AutoField(primary_key=True, serialize=False)),
                ('MaKhoaHoc', models.CharField(max_length=100)),
                ('MaHocVien', models.CharField(max_length=100)),
            ],
        ),
    ]
